/*
 * Waras RESTful API
 *
 * OpenAPI for Waras RESTful API
 *
 * API version: 1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {
	Success bool `json:"success,omitempty"`
}
