/*
 * Waras RESTful API
 *
 * OpenAPI for Waras RESTful API
 *
 * API version: 1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Waras struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Priority float64 `json:"priority,omitempty"`
	Tags []string `json:"tags,omitempty"`
}
